### ISSUE TITLE
GPT rehashing does not work with NVMe

### ISSUE THREAD

**Issue by Vogtinator** [okirch/pcr-oracle#4]
`runtime_disk_for_partition` does not work for device names such as `/dev/nvme0p1`, it tries to open `/dev/nvme0p` instead of `/dev/nvme0`:

```
:::   Trying to re-hash GPT for /dev/nvme0n1p
Error: Unable to open disk device /dev/nvme0n1p: No such file or directory
Fatal: Cannot re-hash PCR for event type EFI_GPT_EVENT
```

IIRC disk names like `/dev/sdp` are also possible, so just removing `p` as well is not correct either. Maybe there's a way to use sysfs for this?

**Comment by aplanas** [comment]
Uhmm then MMC devices should be affected too, as they are under the /dev/mmcblkXpY pattern

**Comment by lcp** [comment]
This patch works for the nvme disk in my laptop.
https://github.com/lcp/pcr-oracle/commit/29d8a1448620854715c4d7c705fc16815760f78a

**Comment by lcp** [comment]
Updated the patch according to the comments from @Vogtinator 
https://github.com/lcp/pcr-oracle/commit/b526dfb940e8dc92845f48792985a39d002c2a44

**Comment by okirch** [comment]
Merged the patch
