### ISSUE TITLE
Tries to read nonexisting (?) EFI variable Shim-605dab50-e046-4300-abb6-3dd810dd8b23

### ISSUE THREAD

**Issue by Vogtinator** [okirch/pcr-oracle#5]
```
::: 0659a: event type=EFI_VARIABLE_AUTHORITY pcr=7 digests=1 data=1184 bytes
:::   --> EFI variable Shim-605dab50-e046-4300-abb6-3dd810dd8b23: 1144 bytes of data
:::   sha256     855e3fe36acc277b003154a875a1d822e28b92e8163c8227dbb406822cb95ddc
:::   Data:
:::         0000  50 ab 5d 60 46 e0 00 43 ab b6 3d d8 10 dd 8b 23 04 00 00 00 00 00 00 00 78 04 00 00 00 00 00 00 P.]`F..C..=....#........x.......
:::         0020  53 00 68 00 69 00 6d 00 30 82 04 74 30 82 03 5c a0 03 02 01 02 02 01 01 30 0d 06 09 2a 86 48 86 S.h.i.m.0..t0..\........0...*.H.
:::         0040  f7 0d 01 01 0b 05 00 30 81 81 31 20 30 1e 06 03 55 04 03 0c 17 6f 70 65 6e 53 55 53 45 20 53 65 .......0..1.0...U....openSUSE.Se
:::         0060  63 75 72 65 20 42 6f 6f 74 20 43 41 31 0b 30 09 06 03 55 04 06 13 02 44 45 31 12 30 10 06 03 55 cure.Boot.CA1.0...U....DE1.0...U
:::         0080  04 07 0c 09 4e 75 72 65 6d 62 65 72 67 31 19 30 17 06 03 55 04 0a 0c 10 6f 70 65 6e 53 55 53 45 ....Nuremberg1.0...U....openSUSE
:::         00a0  20 50 72 6f 6a 65 63 74 31 21 30 1f 06 09 2a 86 48 86 f7 0d 01 09 01 16 12 62 75 69 6c 64 40 6f .Project1!0...*.H........build@o
:::         00c0  70 65 6e 73 75 73 65 2e 6f 72 67 30 1e 17 0d 31 33 30 38 32 36 31 36 31 32 30 37 5a 17 0d 33 35 pensuse.org0...130826161207Z..35
:::         00e0  30 37 32 32 31 36 31 32 30 37 5a 30 81 81 31 20 30 1e 06 03 55 04 03 0c 17 6f 70 65 6e 53 55 53 0722161207Z0..1.0...U....openSUS
:::         0100  45 20 53 65 63 75 72 65 20 42 6f 6f 74 20 43 41 31 0b 30 09 06 03 55 04 06 13 02 44 45 31 12 30 E.Secure.Boot.CA1.0...U....DE1.0
:::         0120  10 06 03 55 04 07 0c 09 4e 75 72 65 6d 62 65 72 67 31 19 30 17 06 03 55 04 0a 0c 10 6f 70 65 6e ...U....Nuremberg1.0...U....open
:::         0140  53 55 53 45 20 50 72 6f 6a 65 63 74 31 21 30 1f 06 09 2a 86 48 86 f7 0d 01 09 01 16 12 62 75 69 SUSE.Project1!0...*.H........bui
:::         0160  6c 64 40 6f 70 65 6e 73 75 73 65 2e 6f 72 67 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 ld@opensuse.org0.."0...*.H......
:::         0180  05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 de df 61 92 7a a4 fe 83 d1 7d 3b 68 0e b1 a7 f0 .......0..........a.z....};h....
:::         01a0  4e 92 93 fc 47 3e 70 2d 4e 88 dc 9a 9e fa 33 b4 a6 db 0e 23 c1 0d a8 c1 d5 65 04 84 04 ff 3a 48 N...G>p-N.....3....#.....e....:H
:::         01c0  18 4f 39 32 e4 ca 4e f9 04 9e 9f 0f cd 20 5d 61 ab a7 00 d8 a5 ff 2b 7f be e8 47 c3 2f 5b 02 c8 .O92..N.......]a......+...G./[..
:::         01e0  bb de 8e 1a e9 46 d3 86 ef ff 88 99 90 eb 10 89 b8 8b 3f 3e a8 07 c6 55 7a 6e d3 5f fc 83 3c 3d .....F............?>...Uzn._..<=
:::         0200  16 ed 26 c5 13 73 92 b1 70 1e 22 95 c8 00 6c 25 76 46 f1 a2 d9 d0 b0 98 68 0f a7 2d b1 0d 67 89 ..&..s..p."...l%vF......h..-..g.
:::         0220  ca 94 4a ea 12 c5 91 55 76 7f 6c 7a 2e f9 18 89 9f f8 f4 24 43 d5 35 6a cb 00 0e 2e ed 4b e2 5d ..J....Uv.lz.......$C.5j.....K.]
:::         0240  09 d8 1b 97 70 99 9e 5a 6f a6 81 a8 9d a9 58 76 7d 69 71 82 d3 ba 3a 96 43 9b f0 da 15 c6 4e e9 ....p..Zo.....Xv}iq...:.C.....N.
:::         0260  c8 15 b9 e9 cb c7 e4 71 ce ea 10 1b 6b c4 2a 70 01 a9 52 b4 17 de 00 52 cf 7d e4 fd 0f 4d 03 18 .......q....k.*p..R....R.}...M..
:::         0280  b2 90 28 d4 6f c4 ae 56 bc 36 60 49 46 8b 6b 0b 02 03 01 00 01 a3 81 f4 30 81 f1 30 0f 06 03 55 ..(.o..V.6`IF.k.........0..0...U
:::         02a0  1d 13 01 01 ff 04 05 30 03 01 01 ff 30 1d 06 03 55 1d 0e 04 16 04 14 68 42 60 0d e2 2c 4c 47 7e .......0....0...U......hB`..,LG~
:::         02c0  95 be 23 df ea 95 13 e5 97 17 62 30 81 ae 06 03 55 1d 23 04 81 a6 30 81 a3 80 14 68 42 60 0d e2 ..#.......b0....U.#...0....hB`..
:::         02e0  2c 4c 47 7e 95 be 23 df ea 95 13 e5 97 17 62 a1 81 87 a4 81 84 30 81 81 31 20 30 1e 06 03 55 04 ,LG~..#.......b......0..1.0...U.
:::         0300  03 0c 17 6f 70 65 6e 53 55 53 45 20 53 65 63 75 72 65 20 42 6f 6f 74 20 43 41 31 0b 30 09 06 03 ...openSUSE.Secure.Boot.CA1.0...
:::         0320  55 04 06 13 02 44 45 31 12 30 10 06 03 55 04 07 0c 09 4e 75 72 65 6d 62 65 72 67 31 19 30 17 06 U....DE1.0...U....Nuremberg1.0..
:::         0340  03 55 04 0a 0c 10 6f 70 65 6e 53 55 53 45 20 50 72 6f 6a 65 63 74 31 21 30 1f 06 09 2a 86 48 86 .U....openSUSE.Project1!0...*.H.
:::         0360  f7 0d 01 09 01 16 12 62 75 69 6c 64 40 6f 70 65 6e 73 75 73 65 2e 6f 72 67 82 01 01 30 0e 06 03 .......build@opensuse.org...0...
:::         0380  55 1d 0f 01 01 ff 04 04 03 02 01 86 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 03 82 01 01 00 U...........0...*.H.............
:::         03a0  8a a3 89 c2 8e d9 f9 82 0b f3 33 ce e9 19 17 17 a3 65 80 cd 33 ae 06 51 56 29 b6 38 87 7b f4 9d ..........3......e..3..QV).8.{..
:::         03c0  fc 28 8e aa e0 53 12 0e 3a 60 c7 06 d8 3a 61 76 3b 77 08 f4 94 a4 8c 7c 47 3a 99 d8 84 9b 17 cc .(...S..:`...:av;w.....|G:......
:::         03e0  20 62 2e e2 76 e4 c6 36 0d 26 e9 2e 53 35 0a fb 3a 35 93 45 c3 93 82 c1 0b f3 08 e9 57 1f 59 37 .b..v..6.&..S5..:5.E........W.Y7
:::         0400  a9 d0 6c 69 fb 68 ea 7f 3b af d3 f7 59 27 8e d4 c7 96 73 f4 0c 0a f7 3e e4 af 6c 8c c7 7a 6f 09 ..li.h..;...Y'....s....>..l..zo.
:::         0420  79 f4 41 1f e3 6f 11 fb 3e 6c b1 a0 7b e4 92 b7 ca f9 32 f5 de c3 b0 73 7d e3 b3 82 5d cd ec 61 y.A..o..>l..{.....2....s}...]..a
:::         0440  dc fe 0c 3e c6 b5 e7 6c 2d 5d 92 73 ff ed aa 6a a9 9b 66 9e 5e 3a 6d 70 b0 31 c0 ce df 2f 21 10 ...>...l-].s...j..f.^:mp.1.../!.
:::         0460  68 0c 87 f3 77 a0 33 31 0a 0f 15 f6 ee 32 88 c5 9a 53 71 cd 0d 1a a1 28 89 d0 bf f6 56 ac 4b 3b h...w.31.....2...Sq....(....V.K;
:::         0480  36 06 2b 01 c5 eb e5 dc 72 83 3d 94 ac 28 83 13 fb c1 5d 27 9c 13 f6 32 5f f6 1f 4a b7 3e 53 8a 6.+.....r.=..(....]'...2_..J.>S.
:::   Firmware hashed entire event data
::: Reading /sys/firmware/efi/efivars/Shim-605dab50-e046-4300-abb6-3dd810dd8b23
::: Reading /sys/firmware/efi/vars/Shim-605dab50-e046-4300-abb6-3dd810dd8b23/data
Fatal: Unable to open file /sys/firmware/efi/vars/Shim-605dab50-e046-4300-abb6-3dd810dd8b23/data: No such file or directory
```

**Comment by Vogtinator** [comment]
Quoting @lcp:

> The "Shim" variable is a fictional variable for the measurement of the built-in certificates...
> https://github.com/rhboot/shim/blob/5c537b3d0cf8c393dad2e61d49aade68f3af1401/README.tpm#L18-L19

**Comment by lcp** [comment]
Another similar situation is the BS variables used by shim: **MokList**, **MokListX**, **MokSBState**, **MokDBState**, and **MokListTrusted**.

The **MokList*** varialbes are mirrored to **RT** variables: **MokListRT**, **MokListXRT**, and **MokListTrustedRT**, and those are accessible in OS, so we can evaluate the contents with the **RT** variables.

Ref: https://github.com/rhboot/shim/blob/main/MokVars.txt#L56-L85

**Comment by lcp** [comment]
Hmmm, the SHIM IPL events for PCR14 are already handled, but the EFI_VARIABLE_AUTHORITY events for PCR7 includes those Mok BS variables, so we have to exclude them as SbatLevel(*).

(*) https://github.com/okirch/pcr-oracle/blob/main/src/efi-variable.c#L121

**Comment by lcp** [comment]
> The **MokList*** varialbes are mirrored to **RT** variables: **MokListRT**, **MokListXRT**, and **MokListTrustedRT**, and those are accessible in OS, so we can evaluate the contents with the **RT** variables.
> 
One thing I forgot is the built-in certificates would be prepended to MokListRT so MokListRT would be a bit different from MokList...

**Comment by okirch** [comment]
> Quoting @lcp:
> 
> > The "Shim" variable is a fictional variable for the measurement of the built-in certificates...
> > https://github.com/rhboot/shim/blob/5c537b3d0cf8c393dad2e61d49aade68f3af1401/README.tpm#L18-L19

The PE/COFF format specifies a certificate data directory (which is excluded when computing the authenticode hash). Would that happen to coincide with the data blob that gets hashed here?

**Comment by lcp** [comment]
The built-in certificates are in the .vendor_cert section, and it can be dumped by objdump:

$ objdump -s -j .vendor_cert /usr/share/efi/x86_64/shim.efi

However, for AArch64, due to lack of proper support in objcopy, the EFI/PE header is hand-crafted in shim and the .vendor_cert section is jammed into .rodata. (The latest binutils now supports AArch64 EFI.)

On the other hand, this is an EFI_VARIABLE_AUTHORITY event, we only need to check if the given raw data exists, not to rehash the whole .vendor_cert section. Since the certificates in .vendor_cert will be prepended to MokListRT, we just map `"Shim"` to `"MokListRT"` in `shim_variables[]`. With the mapping and [my patch](https://github.com/okirch/pcr-oracle/pull/10/commits/6be0acda770d317f36f378515acc9d7ac9471170) for https://github.com/okirch/pcr-oracle/issues/9, the PCR7 digest now matches in my laptop and VM.

**Comment by okirch** [comment]
@lcp, I think it is not sufficient to just rehash the existing data. The "Shim" variable event contains the X509 certificate that the shim uses in verifying the authenticode signature. And that may change during an update of grub, for instance.

I've added some code (well quite a lot of code) to do just that - when we come across the BSA event for the shim loader, we look ahead to the next BSA event. That's the second stage, ie grub. We can extract the authenticode signature from grub's cert_table, which is a pkcs7 signed data blob. From that pkcs7 blob we can extract the X509 cert of the code signer.

**Comment by okirch** [comment]
Fabian, I'd appreciate if you could run another test with this patch (after I've merged the patch that makes nvme devices work :-)

**Comment by lcp** [comment]
> @lcp, I think it is not sufficient to just rehash the existing data. The "Shim" variable event contains the X509 certificate that the shim uses in verifying the authenticode signature. And that may change during an update of grub, for instance.
> 
The grub update is unlikely to change the "Shim" event because it's the CA cert measured in the event. It could happen after a shim update anyway.

> I've added some code (well quite a lot of code) to do just that - when we come across the BSA event for the shim loader, we look ahead to the next BSA event. That's the second stage, ie grub. We can extract the authenticode signature from grub's cert_table, which is a pkcs7 signed data blob. From that pkcs7 blob we can extract the X509 cert of the code signer.

Sounds a good plan. At least pcr-oracle could have the chance to check if the CA cert is in the grub signature.

**Comment by lcp** [comment]
Hmmm this seems not working. The SUSE signature of grub.efi doesn't contain the full chain of certificates but only the SUSE Signing Key. The "Shim" event measures SUSE CA, so the synthesized event doesn't match :-(

**Comment by lcp** [comment]
Another possible way to construct the "Shim" event is to look into the .vendor_cert section.

The section starts with [the following data](https://github.com/rhboot/shim/blob/15.6/cert.S#L29-L33):
```
cert_table:
	.4byte	.Lvendor_authorized_end - vendor_authorized
	.4byte	.Lvendor_deauthorized_end - vendor_deauthorized
	.4byte	vendor_authorized - cert_table
	.4byte	vendor_deauthorized - cert_table
```
Mapping them to the code: `vendor_cert_size`, `vendor_dbx_size`, section offset to `vendor_cert`, and section offset to `vendor_dbx`. With `vendor_cert_size` and `vendor_cert`, it should be sufficient to verify/create the `Shim` event.

However, there are some drawbacks.
1. As mentioned above, AArch64 EFI wasn't supported in the older objcopy. It'd require the latest shim with the [updated ld script](https://github.com/rhboot/shim/commit/d6eb9c6cc7826cea02f31580ac0e56726ae80ad5) and the newer binutils to generate the .vendor_cert section properly.
2. This trick only works with the shim built with `VENDOR_CERT_FILE`. There is another build option, `VENDOR_DB_FILE`, to allow the packager to insert more than one certificate. When `VENDOR_DB_FILE` is used, the "Shim" event will be replaced with a "vendor_db" event. Besides, since there may be more than one certificate, it's hard to predict which one will be used to verify grub.efi. For SUSE/openSUSE shim, it uses `VENDOR_CERT_FILE`, so this shouldn't be a problem for us.

**Comment by Vogtinator** [comment]
> Fabian, I'd appreciate if you could run another test with this patch (after I've merged the patch that makes nvme devices work :-)

It gets further now and with #11 it actually makes it all the way through! Only PCR 7 does not match, but I guess that's expected.

**Comment by okirch** [comment]
Then let's close this issue for the time being. I'd appreciate if you could file another issue for the PCR 7 mismatch, preferably including a testcase generated with pcr-oracle --create-testcase /tmp/my-testcase
